# Generated by Django 5.2.7 on 2025-11-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_usuario_id_alter_usuario_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appi.usuario', to_field='numero_documento', verbose_name='Usuario'),
        ),
    ]
